version: 0
# Allow these tasks to run against any pull request,
# i.e. even people that aren't part of this repo team.
allowPullRequests: public
metadata:
  name: devtools
  description: "Firefox Developer Tools"
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    retries: 0
    # scopes and routes are necessary for the decision task
    # in order to allow creationg tasks using these priviledges
    scopes:
      - "queue:route:index.project.devtools.*"
      - "queue:create-task:aws-provisioner-v1/github-worker"
      - "queue:create-task:aws-provisioner-v1/win2012r2"
      - "github:create-status:ochameau/ff-dt"
      - "github:create-comment:ochameau/ff-dt"
    routes:
      - "index.project.devtools.branches.{{ event.head.repo.branch }}.*"
      - "index.project.devtools.revisions.{{ event.head.sha }}.*"
    extra:
      github:
        events:
          - pull_request.opened
          - pull_request.synchronize
    payload:
      env:
        GITHUB_HEAD_USER_EMAIL: "{{ event.head.user.email }}"
        GITHUB_HEAD_REPO_URL: "{{ event.head.repo.url }}"
        GITHUB_HEAD_REPO_SHA: "{{ event.head.sha }}"
        GITHUB_HEAD_REPO_BRANCH: "{{ event.head.repo.branch }}"
      maxRunTime: 600
      image: 'node:6'
# taskclusterProxy is required to implement a decision task
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "-cx"
        - >
          URL=http://taskcluster/github/v1/repository/ochameau/ff-dt/statuses/{{ event.head.sha }} &&
          JSON="{\"state\":\"error\", \"description\":\"desc\"}" &&
          curl $URL -H "Content-Type: application/json" -X POST -d "$JSON" &&
          URL=http://taskcluster/github/v1/repository/ochameau/ff-dt/issues/{{ event.pullNumber }}/comments &&
          JSON="{\"body\":\"pull request comment from taskcluster\"}" &&
          curl $URL -H "Content-Type: application/json" -X POST -d "$JSON"
    metadata:
      name: task-decision
      description: "Manage tasks"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
